name: > Name goes here < 
description: Quantitative market analysis and forecasting
meta_description: "Quantitative market analysis (mostly cryptos)"
plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://ignaziobovo.com'
gems: [jekyll-paginate]

