name: Machine trading
description: Blogging about stuffs, mostly to impress job recruiters
meta_description: "Online machine learning for trading"
plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

