name: ml_finance.ipynb
description: Quantitative market analysis and forecasting
meta_description: "I don't have enough fantasy for a second description"
plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://ignaziobovo.com'
gems: [jekyll-paginate]

